[package]
name = "day13-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.67"
pest = "2.5.1"
pest_derive = "2.5.1"
util = { version = "0.1.0", path = "../util" }
