[package]
name = "day13-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.67"
nom = "7.1.1"
util = { version = "0.1.0", path = "../util" }
